Bug 1680462 - Dont show search suggestions when disabled
mozilla-extensions/firefox-quick-suggest-keyword pull request #4
Opened 2021-01-13 23:24 UTC by daleharvey

2021-01-13 23:27 UTC, daleharvey commented on tests/browser/browser_test.js
> +  "http://mochi.test:8888/browser/testing/extensions/browser/qs_attribution.sjs?";
This needed added due to a change in PartnerLinkAttribution that appends the campaignID expecting that there is already a queryString

2021-01-13 23:28 UTC, daleharvey commented
Ideally would add tests for private browsing mode as well, however these tests until they run on CI are quite brittle so I would rather have a few working tests than lots of broken ones, can add them if you think they are needed though.

2021-01-14 21:35 UTC, htwyford requested changes
I don't think this check being a part of `matchSearchTerm` makes sense. I'd prefer if you created a new experimental API – maybe `suggestionsEnabled` – that returns a boolean. Then you can call it from `isActive`. I could see `suggestionsEnabled` being useful to other extensions, which would be a plus.

Maybe have `suggestionsEnabled` take a boolean, `isPrivate`, and base the returned value on that rather than getting the top window. So something like

```
// src/background.js -> isActive
let suggestionsEnabled = await browser.experiments.urlbar.suggestionsEnabled(queryContext.isPrivate);
if (!suggestionsEnabled) {
  return;
}

// api.js
XPCOMUtils.defineLazyPreferenceGetter(
  this,
  "searchSuggestionsEnabled",
  "browser.search.suggest.enabled",
  true
);

XPCOMUtils.defineLazyPreferenceGetter(
  this,
  "privateSearchSuggestionsEnabled",
  "browser.search.suggest.enabled.private",
  false
);


...


async function suggestionsEnabled(isPrivate) {
  if (isPrivate) {
    return privateSearchSuggestionsEnabled;
  }
  return searchSuggestionsEnabled;
}

2021-01-14 23:28 UTC, daleharvey commented
Cheers Harry, yeh using the BrowserWindowTracker seemed less than ideal so I do like this much better

2021-01-15 15:02 UTC, htwyford commented on src/background.js
>      this.matchedResult = await api.matchSearchTerm(queryContext.searchString);
After calling async code in `isActive` or `startQuery`, you'll want to check that `isActive`/`startQuery` hasn't been called again -- i.e., the user typed another character in their query. There's boilerplate to do this. At the beginning of the function, we [create an empty object and assign it to a class variable](https://github.com/mozilla-extensions/firefox-quick-suggest-weather/blob/master/src/background.js#L226-L227). Then, after async calls, we [check that the two are still the same](https://github.com/mozilla-extensions/firefox-quick-suggest-weather/blob/master/src/background.js#L262-L264). Could you please add that after these two calls?

2021-01-15 15:03 UTC, htwyford approved these changes
Looks good, thanks! Just one more change

2021-01-18 14:58 UTC, htwyford approved these changes

2021-01-18 14:58 UTC, htwyford commented on src/background.js
> +    }
Please also put this below `await api.matchSearchTerm`

2021-01-18 14:58 UTC, htwyford commented on tests/browser/browser_test.js
> +add_task(async function test_suggestions_disabled() {
Please also add a test for private windows

2021-01-19 17:51 UTC, merged